# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - giziroku-fastapi-docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://giziroku.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ee3848c5ac4d486b91fcc5ec6d59a0fd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cc88b9bd4d3247ea91c72df59d57e340 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: giziroku.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ee3848c5ac4d486b91fcc5ec6d59a0fd }}/giziroku:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'giziroku-fastapi-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1fba7b9c273b48518f6ddfe8f0bbd4c9 }}
        images: 'giziroku.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ee3848c5ac4d486b91fcc5ec6d59a0fd }}/giziroku:${{ github.sha }}'